name: Label issue

on:
  issues:
    types:
      - opened
      - reopened
      - closed

jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Add label on issue open
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        run: |
          gh issue edit ${{ github.event.issue.number }} \
            --add-label "untriaged" \
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Remove label on issue close
        if: github.event.action == 'closed'
        run: |
          gh issue edit ${{ github.event.issue.number }} \
            --remove-label "untriaged"
        env:
          GH_TOKEN: ${{ github.token }}
